### ISSUE TITLE
Option to sanitize netcdf outputs

### ISSUE THREAD

**Issue by sdat2** [obidam/pyxpcm#25]
It seems to be not possible to save a netcdf file because of the key '_pyXpcm_cleanable' in PCM_LABELS.attrs and the other output dataarrays

```
ds.to_netcdf('trial_small.nc', engine='netcdf4')

...

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.setncatts()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._set_att()

TypeError: illegal data type for attribute b'_pyXpcm_cleanable', 
must be one of dict_keys(['S1', 'i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f4', 'f8']), got b1
```

It is simple to remove this keyword from each field, but perhaps there should be an option to automatically remove this.

**Comment by gmaze** [comment]
hi @sdat2 
Thanks for spotting this
It looks like we should simply manage the type of the (internal) attribute ``_pyXpcm_cleanable`` that is required.
working on it ...
