### ISSUE TITLE
Unable to fit the netCDF4 file data using pyXpcm

### ISSUE THREAD

**Issue by Priyanshu-Malik** [obidam/pyxpcm#35]
Don't know if this is how the netCDF4 (sst2010.nc) file is read as can be seen here while dealing with pyXpcm.

the  
"**m.fit(ds, features=features_in_ds, dim=features_zdim)
m**"
code gives the following error :

_xarray.DataArray vertical axis is not deep enough for this PCM axis [0.51 > 0.00]_

Can you take a look and tell me what I am missing here.

Attaching the code here :  
![CODE 1](https://user-images.githubusercontent.com/108738399/177340845-297d6cef-b0c2-4e8b-8da1-0b381b70ac58.jpg)
![CODE 2](https://user-images.githubusercontent.com/108738399/177340855-f9db494f-9077-45b4-bbb8-6491dc24a0a3.jpg)

**Comment by gmaze** [comment]
Hi @Priyanshu-Malik 
the vertical axis must be negative and oriented downward
so, in your case you could:
```python
ds['deptht'] = -np.abs(ds['deptht'])
```
then, to avoid interpolation (because this is a large array and it will take some time), you can use the dataset vertical axis as a PCM axis:
```python
z = ds['deptht'].values[0:40]
pcm_features = {'temperature': z}
```
Here I cut the axis to the first 500m of the water column

and then you can:
```python
features_in_ds = {'temperature': 'votemper'}
m.fit_predict(ds, features=features_in_ds, inplace=True)
```

on my laptop, this took about 37 minutes to run with a PCM of K=12 classes:
```python
ds['PCM_LABELS'].isel(time_counter=0).plot(x='x')
```
![download](https://user-images.githubusercontent.com/1956032/177342890-a9e03a12-488c-446e-8f93-ba6d8a720b97.png)

**Comment by Priyanshu-Malik** [comment]
Worked like a charm, Can't thank you enough and pyxpcm. Took half an hour to run in my laptop as well. 
I was able to follow the rest of the tutorial with ease from that point onward. Got all plots and graphs 

Though, the 'votemper' and 'PCM_LABELS' gave all values in 'nan nan'(attached below) after running the "**m.fit_predict(..)**" code which might have something to do with the dataset itself and not an error, really want to hear about it from you. 

One of the plot :
![Screenshot 2022-07-06 001711](https://user-images.githubusercontent.com/108738399/177395146-56606046-8998-46f4-82f5-921b888c74e4.jpg)
 
![Screenshot 2022-07-06 003505](https://user-images.githubusercontent.com/108738399/177397997-5ee7e5b9-cf45-4148-934c-6b6d46db4c47.jpg)

**Comment by gmaze** [comment]
great ! 
these nans are just a sample of the large array
with this I think we can close this issue then

**Comment by Priyanshu-Malik** [comment]
Hello Sir, been working on the same dataset for a week now, I have to do it for 5 years, so I downloaded the three year data first, making the total size of array about 5 GB. The `m.fit_predict(ds, features=features_in_ds, inplace=True)` command now takes forever to work, along with a warning that says, _Slicing is producing a large chunk_

![Screenshot 2022-07-15 124947](https://user-images.githubusercontent.com/108738399/179173391-6bc8f412-e850-4549-9235-4a9848b4bf78.jpg)

If possible, can you answer these important queries ?

1. Is there a workaround for implementing the model for large size of data ? If no,  just answer the 2nd question which is more important for me.
2. How to determine the optimum number of classes (**k value**), because the tutorial don't have any way to find the value of 
k using BIC elbow method. **We just took random value, like k=12**. Can you please tell me how to find the k value suitable for my dataset using pyXpcm?

**Comment by gmaze** [comment]
Hi @Priyanshu-Malik 

1. 
Did you tried to change the statistic backend from scikit-learn to dask-ml ? 
Install [dask-ml](https://ml.dask.org/) and then use the option ``backend=dask_ml `` when you instantiate your PCM.

If this still does not allow you to classify such a dataset, you can try to check where pyXpcm is getting stalled, following:
https://pyxpcm.readthedocs.io/en/latest/debug_perf.html

Then, my last advice is to subset your dataset to profiles REALY independent from each others, i.e. not closer than a typical correlation scale. It is often the case that the _information_ is redundant in a high resolution dataset, so statistically speaking, there is no need for all profiles for the PCM to be relevant. You should be able to fit a PCM on a subset, and then easily predict classes for the full dataset.

2.
[This is a classic question that depends too much on your specific problem](https://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set). My advice is to compute correctly the BIC (using a correct number of independent samples/profiles) to give you a hint of the statistically allowed range of k, and then to select the k value that make sense for your analysis.
