### ISSUE TITLE
adapt to numpy 1.25

### ISSUE THREAD

**Issue by metzm** [obidam/pyxpcm#42]
Error with numpy 1.25.2:

`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Adjustments needed in
https://github.com/obidam/pyxpcm/blob/master/pyxpcm/models.py#L142
and
https://github.com/obidam/pyxpcm/blob/master/pyxpcm/plot.py#L233

**Comment by gmaze** [comment]
Thanks @metzm for reporting this
Will work on this today and merge a fix asap !
g

**Comment by metzm** [comment]
Thanks for the quick fix!
